[package]
name = "particle"
version = "0.1.0"
authors = ["Dawson Whitehead <dwahme1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
